name: movies_clicks
description: A New Flutter Project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  bloc: ^8.1.0
  built_value: ^8.4.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  fluttertoast: ^8.0.9
  go_router: ^4.4.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.12
  shimmer_pro: ^0.0.6
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.2
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.3+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/black_app_logo.png
  color_dark: "#1F2034"
  image_dark: assets/icon/white_app_logo.png

  android_12:
    image: assets/icon/black_app_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon/white_app_logo.png
    icon_background_color_dark: "#1F2034"

flutter:
  generate: true

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

  assets:
    - assets/images/onboarding/
    - assets/icon/
    - assets/images/
    - assets/fonts/
    - .env

flutter_icons:
  android: "ic_launcher"
  background_color: "#00FFFFFF"
  ios: true
  image_path: "assets/icon/black_app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/white_app_logo.png"
    background_color: "#00FFFFFF"
    theme_color: "#00FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/white_app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/white_app_logo.png"
    icon_size: 48
